export const functionsMeta = [
  {
    displayOnly: false,
    displayName: 'Group By',
    description: 'Group multiple time series by applying an aggregation function.',
    type: 'grouping',
    example: 'Revenue Grouped by Country',
    output: { name: 'Grouped Time Series', description: 'Grouped time series', type: 'multipleTimeSeries' },
    input: [{ name: 'Time Series', description: 'Multiple time series', type: 'multipleTimeSeries' }],
    functionGroup: 'top',
    name: 'groupBy',
    shortName: 'groupBy',
    helpResourceURI: 'https://support.anodot.com/hc/en-us/articles/207926235-GroupBy',
    extendedDescription: 'The Group By function groups rows that have the same values into a single row.',
    parameters: [
      {
        displayType: 'list_single_selection',
        optionalValues: ['Avg', 'Sum', 'Median', 'Max', 'Min', 'Std', 'P90', 'P95', 'P99', 'Count'],
        defaultValue: 'Sum',
        validators: [],
        name: 'Aggregation',
        description: 'Group by aggregation function',
        type: 'string',
        mandatory: false,
      },
      {
        displayType: 'token',
        optionalValues: null,
        validators: [],
        name: 'Group By',
        description: 'Group by fields',
        type: 'string',
        mandatory: true,
      },
    ],
  },
  {
    displayOnly: false,
    displayName: 'Sum',
    description: 'Returns the sum of the input time series list at each time sample.',
    type: 'combined',
    example: '',
    output: { name: 'Sum Time Series', description: 'Sum time series', type: 'singleTimeSeries' },
    input: [
      { name: 'Time Series', description: 'Single time series or a multiple time series', type: 'multipleTimeSeries' },
    ],
    functionGroup: 'top',
    name: 'sumSeries',
    shortName: 'sum',
    helpResourceURI: 'https://support.anodot.com/hc/en-us/articles/207215219-SumSeries',
    extendedDescription: 'Sum a group of metrics',
    parameters: [],
  },
  {
    displayOnly: false,
    displayName: 'Scale',
    description: 'Scales each sample in the input time series with the constant provided.',
    type: 'transform',
    example: '',
    output: { name: 'Transformed Time Series', description: 'Transformed time series', type: 'multipleTimeSeries' },
    input: [
      { name: 'Time Series', description: 'Single time series or a multiple time series', type: 'multipleTimeSeries' },
    ],
    functionGroup: 'top',
    name: 'scale',
    shortName: 'scale',
    helpResourceURI: 'https://support.anodot.com/hc/en-us/articles/207215199-Scale',
    extendedDescription: 'Multiplies each data point by the provided scale factor',
    parameters: [
      {
        displayType: 'numeric',
        optionalValues: null,
        validators: [
          { name: 'null', parameters: {} },
          { name: 'nan', parameters: {} },
          { name: 'finite', parameters: {} },
        ],
        name: 'Scale Factor',
        description: 'Scale Factor',
        type: 'double',
        mandatory: true,
      },
    ],
  },
  {
    displayOnly: false,
    displayName: 'Ratio Pairs',
    description: 'Divides one or more time-series by another time-series',
    type: 'transform',
    example: '',
    output: { name: 'Transformed Time Series', description: 'Transformed time series', type: 'multipleTimeSeries' },
    input: [
      { name: 'Time Series', description: 'Single time series or a multiple time series', type: 'multipleTimeSeries' },
    ],
    functionGroup: 'top',
    name: 'ratioPairs',
    shortName: 'ratioPairs',
    helpResourceURI: 'https://support.anodot.com/hc/en-us/articles/115002021094-ratioPairs',
    extendedDescription: 'Divides one or more time-series by another time-series',
    parameters: [
      {
        displayType: 'numeric',
        optionalValues: null,
        validators: [
          { name: 'null', parameters: {} },
          { name: 'nan', parameters: {} },
          { name: 'finite', parameters: {} },
        ],
        name: 'metrics',
        description: 'Divides one or more time-series by another time-series',
        type: 'double',
        mandatory: true,
      },
    ],
  },
];
